//! Per-detector budget soak (Phase 6 exit work).
//!
//! The pipeline-level robustness soak proves the whole lane survives hostile
//! input; this test isolates each detector so a pathological one is named and
//! measured on its own. Every detector runs over a deterministic hostile
//! corpus (LCG-generated byte soup + targeted shapes) and must:
//!
//! - never panic (a malformed request must not take the edge down),
//! - keep every finding count bounded (no unbounded result growth),
//! - report degradations as non-empty reasons when it declines to inspect,
//! - finish the corpus inside a generous per-detector budget — the bound
//!   catches catastrophic regressions (regex bombs, accidental quadratic
//!   work), not micro-variation; the measured baseline is printed.
//!
//! Run with:
//!
//! ```text
//! cargo test -p varman-waf --test detector_budgets -- --nocapture
//! ```

use std::time::{Duration, Instant};

use varman_waf::canonical::{Canonicalizer, RequestParts};
use varman_waf::pipeline::fast::{
    ProtocolDetector, RawPathTraversalDetector, SignatureDetector,
};
use varman_waf::pipeline::semantic::{
    BodyShapeDetector, CommandInjectionDetector, DeserializationDetector,
    DlpDetector, GraphqlAbuseDetector, HtmlXssDetector, JwtDetector,
    LdapXPathDetector, NosqlInjectionDetector, PrototypePollutionDetector,
    SqlStructuralDetector, SsrfStructuralDetector, SstiDetector, TiDetector,
    WebSocketDetector, XxeDetector,
};
use varman_waf::pipeline::DetectionContext;
use varman_waf::pipeline::Detector;

/// Deterministic pseudo-random generator (LCG) for reproducible inputs.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0
    }

    fn bytes(&mut self, len: usize) -> Vec<u8> {
        (0..len).map(|_| (self.next() >> 24) as u8).collect()
    }
}

/// Hostile corpus: byte soup plus targeted shapes.
fn hostile_inputs() -> Vec<RequestParts> {
    let mut cases: Vec<RequestParts> = Vec::new();
    let mut rng = Lcg(0x5eed_1234_abcd_0001);
    for index in 0..200 {
        let len = 1 + (index * 7) % 512;
        let bytes = rng.bytes(len);
        let value = String::from_utf8_lossy(&bytes).into_owned();
        let encoded = value
            .replace('%', "%25")
            .replace('&', "%26")
            .replace('#', "%23")
            .replace(' ', "%20");
        cases.push(
            RequestParts::new("POST", "example.com", format!("/?p={encoded}"))
                .with_header("User-Agent", value.clone())
                .with_header("Content-Type", "application/json")
                .with_body(bytes),
        );
    }
    // Targeted hostile shapes.
    let deep = format!("{}{}", "{\"a\":".repeat(64), "}".repeat(64));
    cases.push(
        RequestParts::new("POST", "example.com", "/api")
            .with_header("Content-Type", "application/json")
            .with_body(deep.into_bytes()),
    );
    cases.push(
        RequestParts::new("GET", "example.com", "/")
            .with_header("Upgrade", "websocket")
            .with_header("Origin", "null")
            .with_header("User-Agent", "sqlmap/1.7")
            .with_header("Authorization", "Bearer eyJhbGciOiJub25lIn0.e30."),
    );
    cases.push(
        RequestParts::new("GET", "example.com", "/")
            .with_header("Content-Length", "abc")
            .with_header("Transfer-Encoding", "chunked"),
    );
    let huge = "A".repeat(200_000);
    cases.push(RequestParts::new(
        "GET",
        "example.com",
        format!("/?q={huge}"),
    ));
    cases
}

fn detectors() -> Vec<Box<dyn Detector>> {
    vec![
        Box::new(ProtocolDetector::new()),
        Box::new(SignatureDetector::new()),
        Box::new(RawPathTraversalDetector::new()),
        Box::new(SqlStructuralDetector::new()),
        Box::new(HtmlXssDetector::new()),
        Box::new(CommandInjectionDetector::new()),
        Box::new(SsrfStructuralDetector::new()),
        Box::new(NosqlInjectionDetector::new()),
        Box::new(SstiDetector::new()),
        Box::new(XxeDetector::new()),
        Box::new(DeserializationDetector::new()),
        Box::new(PrototypePollutionDetector::new()),
        Box::new(LdapXPathDetector::new()),
        Box::new(GraphqlAbuseDetector::new()),
        Box::new(JwtDetector::new()),
        Box::new(DlpDetector::new()),
        Box::new(BodyShapeDetector::new()),
        Box::new(TiDetector::starter()),
        Box::new(WebSocketDetector::new()),
    ]
}

#[test]
fn every_detector_stays_within_its_budget() {
    let canonicalizer = Canonicalizer::default();
    let inputs: Vec<_> = hostile_inputs()
        .into_iter()
        .map(|parts| canonicalizer.canonicalize(parts))
        .collect();
    let detectors = detectors();
    assert!(detectors.len() >= 19, "detector set shrank unexpectedly");

    let mut failures: Vec<String> = Vec::new();
    println!(
        "\n=== per-detector budget soak ({} inputs) ===",
        inputs.len()
    );
    println!("{:<42} {:>10} {:>10}", "detector", "ms", "findings");
    println!("{:-<42} {:->10} {:->10}", "", "", "");

    for detector in &detectors {
        let name = detector.id().as_str();
        let start = Instant::now();
        let mut findings_total = 0usize;
        for request in &inputs {
            let mut ctx = DetectionContext::new();
            let result = detector.inspect(request, &mut ctx);
            findings_total += result.findings.len();
            if result.findings.len() > 64 {
                failures.push(format!(
                    "{name}: unbounded findings ({}) for one input",
                    result.findings.len()
                ));
            }
            if let Some(reason) = result.degraded {
                if reason.trim().is_empty() {
                    failures.push(format!("{name}: empty degradation reason"));
                }
            }
        }
        let elapsed = start.elapsed();
        println!(
            "{:<42} {:>10.2} {:>10}",
            name,
            elapsed.as_secs_f64() * 1000.0,
            findings_total
        );
        if elapsed > Duration::from_millis(1500) {
            failures.push(format!(
                "{name}: corpus took {:.1} ms (budget 1500 ms)",
                elapsed.as_secs_f64() * 1000.0
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "per-detector budget failures:\n{}",
        failures.join("\n")
    );
}
